apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fallback-ing-svc
  namespace: app
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: fallback-svc
          servicePort: 80
